baseURL = "/"
defaultContentLanguage  = "en"

title = "Trafiklab"

# Theme is loaded through a git submodule
theme = "trafiklab-2021"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

refLinksErrorLevel = "WARNING"

[module]
[module.hugoVersion]
extended = true
max = ""
min = "0.87.0"

# paths
[permalinks]
  "/" = "/:title/"
  posts = "/:section/:title/"

# Multilingual
[languages]
  [languages.en]
  languageName = "English"
  weight = 2

  [languages.sv]
  languageName = "Svenska"
  weight = 1
    [languages.sv.permalinks]
      news = "nyheter/:year/:month/:title/"
      cases = "fallstudier/:year/:month/:title/"

# HTML for shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.dcat]
    isPlainText = false
    isHTML = false
    permalinkable = true
    mediaType = "application/rdf+xml"
    rel = "alternate"
    protocol = "http://"

[mediaTypes]
  [mediaTypes."application/rdf+xml"]
    suffixes = ["rdf"]

[params]
  devPortalUrl = "https://developer.trafiklab.se"
  sourceRepository = "https://github.com/trafiklab/trafiklab.se/"
  sourceRepositoryBranch = "main"
  support = "https://support.trafiklab.se/"
  mailchimpId = "32daffb7a6"
  mailchimpUser = "f850700e99947106e6a19cfaa"
  mailchimpAccount = "trafiklab.us20"
