---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/api
  label: Apis
  create: all
  match: "**/*"
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: content/cases
  label: Cases
  create: all
  match: "**/*"
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content
  label: All pages
  create: all
  match: "*"
- type: heading
  label: Blocks
- type: directory
  path: content/headless/footer
  label: Footer logos
  create: documents
  match: "**/*"
- type: directory
  path: content/headless/about
  label: Contacts (About)
  create: documents
  match: "*"
- type: directory
  path: content/headless
  label: Front CTAs
  create: none
  match: front*.md
upload_dir: assets/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.87.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public --config=config/config.toml
version: 0.81.0
